server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
#Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /index.html

#Security
security:
  jwt:
    header: "Authorization"
    prefix: "Bearer "
    secret: "demo_oracle_db"
    expiration: "#{2*60*60}"
    refresh-expiration: "#{7*24*60*60}"

spring:
  #  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: "jdbc:oracle:thin:@10.10.0.202:1521:ORCL"
#    username: demo
#    password: demo
#    name: DEMO
#    hikari:
#      auto-commit: false
#  jpa:
#    database-platform: org.hibernate.dialect.OracleDialect
#    database: oracle
#    show-sql: true
#    properties:
#      hibernate.id.new_generator_mappings: true
#      hibernate.connection.provider_disables_autocommit: true
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false
  datasource:
    url: jdbc:mysql://localhost:3306/DEMO?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&lower_case_table_names=1
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      enabled: true
      resolve-lazily: true